version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wad-calendar-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wad_calendar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./src/main/resources/credentials:/app/credentials
    networks:
      - wad-network

  db:
    image: postgres:14-alpine
    container_name: wad-calendar-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wad_calendar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wad-network

networks:
  wad-network:
    driver: bridge

volumes:
  postgres-data:
